# Generated by Django 5.1.4 on 2026-09-29 18:33

import django.db.models.deletion
import ocr.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(max_length=500, upload_to=ocr.models.upload_path)),
                ('file_type', models.CharField(max_length=16)),
                ('num_pages', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('error_stage', models.CharField(blank=True, choices=[('upload', 'Upload'), ('pdf_conversion', 'PDF conversion'), ('preprocessing', 'Preprocessing'), ('ocr', 'OCR'), ('extraction', 'Extraction'), ('validation', 'Validation'), ('database', 'Database'), ('export', 'Export')], max_length=32)),
                ('error_type', models.CharField(blank=True, max_length=128)),
                ('error_message', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('share_type', models.CharField(blank=True, max_length=64, null=True)),
                ('certificate_no', models.CharField(blank=True, max_length=64, null=True)),
                ('share_holder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_shares', models.IntegerField(blank=True, null=True)),
                ('face_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('distinctive_from', models.CharField(blank=True, max_length=32, null=True)),
                ('distinctive_to', models.CharField(blank=True, max_length=32, null=True)),
                ('date_of_issue', models.CharField(blank=True, max_length=32, null=True)),
                ('registered_folio_no', models.CharField(blank=True, max_length=64, null=True)),
                ('present_share_holder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('present_transfer_date', models.CharField(blank=True, max_length=32, null=True)),
                ('present_folio_no', models.CharField(blank=True, max_length=64, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('page_number', models.PositiveSmallIntegerField(default=1)),
                ('overall_confidence', models.FloatField(default=0.0)),
                ('needs_review', models.BooleanField(default=False)),
                ('validation_status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('validation_flags', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='ocr.document')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OCRJob',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('engine', models.CharField(choices=[('paddleocr_gpu', 'PaddleOCR (NVIDIA GPU)'), ('paddleocr_cpu', 'PaddleOCR (CPU)')], default='paddleocr_cpu', max_length=32)),
                ('worker_count', models.PositiveSmallIntegerField(default=8)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('paused', 'Paused'), ('stopped', 'Stopped'), ('complete', 'Complete'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('total_files', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ocr.ocrjob'),
        ),
        migrations.CreateModel(
            name='TransferRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transfer_date', models.CharField(blank=True, max_length=32, null=True)),
                ('transfer_no', models.CharField(blank=True, max_length=64, null=True)),
                ('transferee_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ledger_folio_no', models.CharField(blank=True, max_length=64, null=True)),
                ('authorised_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('row_index', models.PositiveSmallIntegerField(default=0)),
                ('confidence', models.FloatField(default=0.0)),
                ('needs_review', models.BooleanField(default=False)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='ocr.certificate')),
            ],
            options={
                'ordering': ['certificate_id', 'row_index'],
            },
        ),
        migrations.CreateModel(
            name='ValidationResult',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rule_name', models.CharField(max_length=64)),
                ('passed', models.BooleanField()),
                ('message', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_results', to='ocr.certificate')),
            ],
        ),
        migrations.CreateModel(
            name='CertificateField',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(choices=[('certificate_no', 'Certificate No'), ('company_name', 'Company Name'), ('share_holder_name', 'Share Holder Name'), ('number_of_shares', 'Number of Shares'), ('face_value', 'Face Value'), ('share_type', 'Share Type'), ('date_of_issue', 'Date of Issue'), ('distinctive_from', 'Distinctive From'), ('distinctive_to', 'Distinctive To'), ('registered_folio_no', 'Registered Folio No')], max_length=64)),
                ('value', models.TextField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(default='paddleocr', max_length=32)),
                ('page', models.PositiveSmallIntegerField(default=1)),
                ('region', models.CharField(blank=True, max_length=64)),
                ('needs_review', models.BooleanField(default=False)),
                ('reviewed', models.BooleanField(default=False)),
                ('reviewed_value', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='ocr.certificate')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('certificate', 'field_name')},
            },
        ),
    ]
